{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spheraform.fullname" . }}-redis
  labels:
    {{- include "spheraform.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spheraform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "spheraform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        {{- if .Values.redis.appendonly }}
        command: ["redis-server", "--appendonly", "yes"]
        {{- end }}
        ports:
        - containerPort: 6379
          name: redis
        {{- if .Values.redis.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /data
        {{- end }}
        {{- if .Values.redis.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: {{ .Values.redis.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.livenessProbe.periodSeconds }}
        {{- end }}
        {{- if .Values.redis.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
      {{- if .Values.redis.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "spheraform.fullname" . }}-redis-data
      {{- end }}
{{- end }}
