{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spheraform.fullname" . }}-redis
  labels:
    {{- include "spheraform.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "spheraform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
{{- end }}
