{{- if .Values.martin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spheraform.fullname" . }}-martin
  labels:
    {{- include "spheraform.labels" . | nindent 4 }}
    app.kubernetes.io/component: martin
spec:
  type: ClusterIP
  selector:
    {{- include "spheraform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: martin
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
{{- end }}
