{{- if and .Values.minio.enabled .Values.minio.setup.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spheraform.fullname" . }}-minio-setup
  labels:
    {{- include "spheraform.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio-setup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "spheraform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio-setup
    spec:
      containers:
      - name: mc
        image: "{{ .Values.minio.setup.image.repository }}:{{ .Values.minio.setup.image.tag }}"
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for MinIO to be ready..."
          sleep 20
          mc alias set myminio http://{{ include "spheraform.fullname" . }}-minio:9000 {{ .Values.minio.rootUser }} {{ .Values.minio.rootPassword }}
          mc mb myminio/{{ .Values.minio.bucket }} --ignore-existing
          mc anonymous set download myminio/{{ .Values.minio.bucket }}
          echo "MinIO setup complete!"
        env:
        - name: MC_HOST_myminio
          value: "http://{{ .Values.minio.rootUser }}:{{ .Values.minio.rootPassword }}@{{ include "spheraform.fullname" . }}-minio:9000"
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
