{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spheraform.fullname" . }}-postgres-config
  labels:
    {{- include "spheraform.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
data:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- end }}
