{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spheraform.fullname" . }}-postgres
  labels:
    {{- include "spheraform.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spheraform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "spheraform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "spheraform.fullname" . }}-postgres-config
        ports:
        - containerPort: 5432
          name: postgres
        {{- if .Values.postgres.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        {{- end }}
        {{- if .Values.postgres.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -h localhost -U {{ .Values.postgres.username }}
          initialDelaySeconds: {{ .Values.postgres.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.postgres.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.postgres.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.postgres.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -h localhost -U {{ .Values.postgres.username }}
          initialDelaySeconds: {{ .Values.postgres.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.postgres.readinessProbe.periodSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
      {{- if .Values.postgres.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "spheraform.fullname" . }}-postgres-data
      {{- end }}
{{- end }}
