{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spheraform.fullname" . }}-postgres
  labels:
    {{- include "spheraform.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "spheraform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
{{- end }}
